title: "MÅ¯j Blog"
description: "Tohle je test"
url: "https://stepanjirkakarasek.github.io"
baseurl: ""
author: "Stepan Jirka Karasek"
lang: cs

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
timezone: Europe/Prague

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
